[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ISOAP = "75e88e8e-8488-4b14-bf8c-a5e98e21fac3"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
VOFTools = "f4b4545c-59ad-49ee-afe8-a74df8bf51d2"
gVOF = "04ededa1-a232-4018-ac62-0847248ccfed"

[compat]
Documenter = "1"
